[package]
name = "bevy-technical-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
tokio = { version = "1.20.1", features = ["full"] }

[features]
client = []
headless = []
editor = []
server = []
